<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>d76f758f-a0c6-4552-a545-225ed9e0ecf7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Qdrant" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" />
	<PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QdrantLoad\QdrantLoad.csproj" />
    <ProjectReference Include="..\USMAgent.AIService.API\USMAgent.AIService.API.csproj" />
	<ProjectReference Include="..\USMAgent.MigrationService\USMAgent.MigrationService.csproj" />
  </ItemGroup>

</Project>
