// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using USMAgent.Infrastructure.Persistence;

#nullable disable

namespace USMAgent.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupScheduleEntry", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleEntriesId")
                        .HasColumnType("integer");

                    b.HasKey("GroupsId", "ScheduleEntriesId");

                    b.HasIndex("ScheduleEntriesId");

                    b.ToTable("GroupScheduleEntry", (string)null);
                });

            modelBuilder.Entity("ScheduleEntryTeacher", b =>
                {
                    b.Property<int>("ScheduleEntriesId")
                        .HasColumnType("integer");

                    b.Property<int>("TeachersId")
                        .HasColumnType("integer");

                    b.HasKey("ScheduleEntriesId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("ScheduleEntryTeacher", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.AcademicPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("AcademicPeriods", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.CourseAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Alias");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseAliases", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.ScheduleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Alternative")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("LessonType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Parity")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Specialization")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Subgroup")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("AcademicPeriodId", "DayOfWeek", "TimeSlotId");

                    b.ToTable("ScheduleEntries", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LastName");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SlotNumber")
                        .IsUnique();

                    b.ToTable("TimeSlots", (string)null);
                });

            modelBuilder.Entity("GroupScheduleEntry", b =>
                {
                    b.HasOne("USMAgent.Domain.Entities.Schedule.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USMAgent.Domain.Entities.Schedule.ScheduleEntry", null)
                        .WithMany()
                        .HasForeignKey("ScheduleEntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleEntryTeacher", b =>
                {
                    b.HasOne("USMAgent.Domain.Entities.Schedule.ScheduleEntry", null)
                        .WithMany()
                        .HasForeignKey("ScheduleEntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USMAgent.Domain.Entities.Schedule.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.CourseAlias", b =>
                {
                    b.HasOne("USMAgent.Domain.Entities.Schedule.Course", "Course")
                        .WithMany("Aliases")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.ScheduleEntry", b =>
                {
                    b.HasOne("USMAgent.Domain.Entities.Schedule.AcademicPeriod", "AcademicPeriod")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("USMAgent.Domain.Entities.Schedule.Course", "Course")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("USMAgent.Domain.Entities.Schedule.Room", "Room")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("USMAgent.Domain.Entities.Schedule.TimeSlot", "TimeSlot")
                        .WithMany("ScheduleEntries")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("Course");

                    b.Navigation("Room");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.AcademicPeriod", b =>
                {
                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.Course", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.Room", b =>
                {
                    b.Navigation("ScheduleEntries");
                });

            modelBuilder.Entity("USMAgent.Domain.Entities.Schedule.TimeSlot", b =>
                {
                    b.Navigation("ScheduleEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
